#!C:\Users\ehich\Documents\Data Analysis projects\credit_card_insurance_use\myenv\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
